version: '3'
services:
  service-a:
    build:
      context: ./dataHandler
      dockerfile: Dockerfile
    ports:
      - 8082:8082
  service-b:  
    build:    
      context: ./medicineHandler 
      dockerfile: Dockerfile 
    ports: 
      - 8081:8081
  service-c:  
    build:    
      context: ./notificationsHandler 
      dockerfile: Dockerfile 
    ports: 
      - 8083:8083
          
  api-gateway:   
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - service-a
      - service-b
      - service-c